version: '2'
services:
  mongo:
    image: mongo:2.6
    expose:
      - "27017"
    ports:
      - "27017:27017"
  api-service:
    image: rafaelb/api-service:v1
    ports:
      - "1337:1337"
    depends_on:
      - mongo